aliyun:
    oss:
        bucketName: web-tilas-wfw
        endpoint: https://oss-cn-beijing.aliyuncs.com

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.ithbu.tilas.mybatis.entity
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/tilas
        username: root
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
server:
    port: 8080
logging:
    level:
        org.springframework.jdbc.support.JdbcTransactionManager: debug